export const metadata = {
  title: "เกี่ยวกับ",
  description: "Generated by create next app",
};

export default function About() {
  const topics: string[] = ["HTML", "CSS", "TypeScript", "Next.js"];
  return (
    <main className="page">
      <h1>เกี่ยวกับเว็บไซต์นี้</h1>
        <p>
          Student Course Hub คือเว็บไซต์ที่พัฒนาขึ้นเพื่อรวบรวมข้อมูลรายวิชาของหลักสูตร
          ให้นักศึกษาสามารถตรวจสอบรหัสวิชา ชื่อวิชา จำนวนหน่วยกิต
          และสถานะการเปิดลงทะเบียนได้จากที่เดียว
        </p>

      <div className="boxhide"></div>
      <h2>Topics - เทคโนโลยีที่ใช้พัฒนา</h2>
      <ul>
        {topics.map((topic) => (
        <li key={topic}>{topic}</li>
        ))}
      </ul>
      </main>
  );
}